redis:
  image:redis
db:
  image: postgres:9.4
vote:
  image: unit
  ports:
    - 5000:80
  links:
    - redis
result:
  image: lolmeida/result-app
  ports:
    - 5001:80
  links:
    - db
worker:
  image: worker   
  links:
    - redis
    - db
